In [1]:
import numpy as np


In [14]:
a = np.arange(15)
print(a)
a = np.arange(15).reshape(3, 5)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [25]:
list_b = [1,2,3,4,5,6,7,8,9]
b = np.array(list_b).reshape(3, 3)
print(b)

In [26]:
b = np.array([(1,2,3), (7,8,9)])
print(b)
print(b)

[[1 2 3]
 [7 8 9]]


In [37]:
c = np.array([ [1,3], [3,4]] , dtype = complex)
print(c)

[[1.+0.j 3.+0.j]
 [3.+0.j 4.+0.j]]


In [38]:
zeros = np.zeros((9,5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [34]:
ones = np.ones( (2,3,4), dtype=np.int16)
print(ones)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [39]:
cd = np.arange(0,7,0.8)
print(cd)

[0.  0.8 1.6 2.4 3.2 4.  4.8 5.6 6.4]


In [40]:
np.linspace(0,9,8)

array([0.        , 1.28571429, 2.57142857, 3.85714286, 5.14285714,
       6.42857143, 7.71428571, 9.        ])

In [41]:
a = np.array([20,30,40,50])
b = np.array(4)
c = a-b 

In [42]:
b**2
10*np.sin(a)
a<35

array([ True,  True, False, False])

In [46]:
a = np.array([[1,1],[0,1]])
b = np.array([[2,0],[3,4]])
prod1 = a * b
prod2 = a @ b
prod = a.dot(b)
print(prod1)
print(prod2)
print(prod)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [59]:
a = np.ones((2,3),dtype=int)
b=np.random.random((2,3))
a *= 3 
b += a

In [56]:
a = np.random.random((2,3))
a.sum()

3.186209723966027

In [54]:
a.min()

0.007908651967798774

In [55]:
a.max()

0.9187026656965133